Disable non-mac workflows for now

diff --git a/.github/workflows/failover.yml b/.github/workflows/failover.yml
--- a/.github/workflows/failover.yml
+++ b/.github/workflows/failover.yml
@@ -20,158 +20,158 @@ env:
   WINDOWS_BUILD_TYPE: Debug
 
 jobs:
-  build-windows:
-    name: Windows
-    runs-on: windows-2019
-    env:
-      CMAKE_GENERATOR: Visual Studio 16 2019
-      MYSQL_DIR: C:/mysql-8.0.28-winx64
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v2
+  # build-windows:
+  #   name: Windows
+  #   runs-on: windows-2019
+  #   env:
+  #     CMAKE_GENERATOR: Visual Studio 16 2019
+  #     MYSQL_DIR: C:/mysql-8.0.28-winx64
+  #   steps:
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v2
 
-      # Configure build environment/dependencies
-      - name: Cache MySQL client libs and include files
-        id: cache-mysql
-        uses: actions/cache@v3
-        with:
-          path: |
-            C:/mysql-8.0.28-winx64/
-          key: ${{ runner.os }}-mysql-${{ hashFiles('**/VersionInfo.h') }}
+  #     # Configure build environment/dependencies
+  #     - name: Cache MySQL client libs and include files
+  #       id: cache-mysql
+  #       uses: actions/cache@v3
+  #       with:
+  #         path: |
+  #           C:/mysql-8.0.28-winx64/
+  #         key: ${{ runner.os }}-mysql-${{ hashFiles('**/VersionInfo.h') }}
 
-      - name: Install MySQL client libs and include files
-        if: steps.cache-mysql.outputs.cache-hit != 'true'
-        run: |
-          curl https://cdn.mysql.com/archives/mysql-8.0/mysql-8.0.28-winx64.zip -o mysql.zip
-          curl https://cdn.mysql.com/archives/mysql-8.0/mysql-8.0.28-winx64-debug-test.zip -o mysql-debug.zip
-          unzip -d C:/ mysql.zip
-          mkdir C:/mysql-8.0.28-winx64-debug
-          unzip -d C:/mysql-8.0.28-winx64-debug mysql-debug.zip
-          mv -Force C:/mysql-8.0.28-winx64-debug/mysql-8.0.28-winx64/lib/debug/mysqlclient.lib C:/mysql-8.0.28-winx64/lib/mysqlclient.lib
+  #     - name: Install MySQL client libs and include files
+  #       if: steps.cache-mysql.outputs.cache-hit != 'true'
+  #       run: |
+  #         curl https://cdn.mysql.com/archives/mysql-8.0/mysql-8.0.28-winx64.zip -o mysql.zip
+  #         curl https://cdn.mysql.com/archives/mysql-8.0/mysql-8.0.28-winx64-debug-test.zip -o mysql-debug.zip
+  #         unzip -d C:/ mysql.zip
+  #         mkdir C:/mysql-8.0.28-winx64-debug
+  #         unzip -d C:/mysql-8.0.28-winx64-debug mysql-debug.zip
+  #         mv -Force C:/mysql-8.0.28-winx64-debug/mysql-8.0.28-winx64/lib/debug/mysqlclient.lib C:/mysql-8.0.28-winx64/lib/mysqlclient.lib
             
-      - name: Create build environment
-        shell: bash
-        run: cmake -E make_directory ${{ github.workspace }}/build
+  #     - name: Create build environment
+  #       shell: bash
+  #       run: cmake -E make_directory ${{ github.workspace }}/build
 
-      - name: Configure CMake
-        shell: bash
-        run: cmake -S . -B build -A x64
-                -G "$CMAKE_GENERATOR"
-                -DCMAKE_BUILD_TYPE=$WINDOWS_BUILD_TYPE
-                -DMYSQLCLIENT_STATIC_LINKING=TRUE
-                -DENABLE_UNIT_TESTS=TRUE
-                -DENABLE_INTEGRATION_TESTS=FALSE
+  #     - name: Configure CMake
+  #       shell: bash
+  #       run: cmake -S . -B build -A x64
+  #               -G "$CMAKE_GENERATOR"
+  #               -DCMAKE_BUILD_TYPE=$WINDOWS_BUILD_TYPE
+  #               -DMYSQLCLIENT_STATIC_LINKING=TRUE
+  #               -DENABLE_UNIT_TESTS=TRUE
+  #               -DENABLE_INTEGRATION_TESTS=FALSE
 
-      # Configure test environment
-      - name: Build Driver
-        shell: bash
-        working-directory: ${{ github.workspace }}/build
-        run: |
-          cmake --build . --config $WINDOWS_BUILD_TYPE
+  #     # Configure test environment
+  #     - name: Build Driver
+  #       shell: bash
+  #       working-directory: ${{ github.workspace }}/build
+  #       run: |
+  #         cmake --build . --config $WINDOWS_BUILD_TYPE
 
-      - name: Run failover tests
-        if: always()
-        working-directory: ${{ github.workspace }}/build/testing
-        shell: bash
-        run: ctest -C $WINDOWS_BUILD_TYPE --output-on-failure
+  #     - name: Run failover tests
+  #       if: always()
+  #       working-directory: ${{ github.workspace }}/build/testing
+  #       shell: bash
+  #       run: ctest -C $WINDOWS_BUILD_TYPE --output-on-failure
 
-      - name: Check memory leaks
-        if: always()
-        working-directory: ${{ github.workspace }}/build/testing/Testing/Temporary
-        run:  |
-          $is_leaking = Select-String -Path ./LastTest.log -Pattern 'leak' -SimpleMatch
-          if ($is_leaking) {echo $is_leaking; exit 1;}
+  #     - name: Check memory leaks
+  #       if: always()
+  #       working-directory: ${{ github.workspace }}/build/testing/Testing/Temporary
+  #       run:  |
+  #         $is_leaking = Select-String -Path ./LastTest.log -Pattern 'leak' -SimpleMatch
+  #         if ($is_leaking) {echo $is_leaking; exit 1;}
 
-      # Upload artifacts
-      - name: Upload build artifacts - Binaries
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: windows-failover-sln
-          path: ${{ github.workspace }}/build/MySQL_Connector_ODBC.sln
-      - name: Upload build artifacts - Binaries
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: windows-failover-binaries
-          path: ${{ github.workspace }}/build/bin/
-      - name: Upload build artifacts - Libraries
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: windows-failover-libraries
-          path: ${{ github.workspace }}/build/lib/
-      - name: Upload failover test artifacts
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: windows-failover-results
-          path: ${{ github.workspace }}/build/testing/Testing/Temporary/LastTest.log
+  #     # Upload artifacts
+  #     - name: Upload build artifacts - Binaries
+  #       if: always()
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: windows-failover-sln
+  #         path: ${{ github.workspace }}/build/MySQL_Connector_ODBC.sln
+  #     - name: Upload build artifacts - Binaries
+  #       if: always()
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: windows-failover-binaries
+  #         path: ${{ github.workspace }}/build/bin/
+  #     - name: Upload build artifacts - Libraries
+  #       if: always()
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: windows-failover-libraries
+  #         path: ${{ github.workspace }}/build/lib/
+  #     - name: Upload failover test artifacts
+  #       if: always()
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: windows-failover-results
+  #         path: ${{ github.workspace }}/build/testing/Testing/Temporary/LastTest.log
 
-  build-linux:
-    name: Linux
-    runs-on: ubuntu-latest
-    env:
-      CMAKE_GENERATOR: Unix Makefiles
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v2
+  # build-linux:
+  #   name: Linux
+  #   runs-on: ubuntu-latest
+  #   env:
+  #     CMAKE_GENERATOR: Unix Makefiles
+  #   steps:
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v2
 
-      # Configure build environment/dependencies
-      - name: Install MySQL client libs & other dependencies
-        run: sudo apt-get update && sudo apt-get install 
-                build-essential 
-                libgtk-3-dev 
-                libmysqlclient-dev 
-                unixodbc
-                unixodbc-dev
+  #     # Configure build environment/dependencies
+  #     - name: Install MySQL client libs & other dependencies
+  #       run: sudo apt-get update && sudo apt-get install 
+  #               build-essential 
+  #               libgtk-3-dev 
+  #               libmysqlclient-dev 
+  #               unixodbc
+  #               unixodbc-dev
 
-      - name: Create build environment
-        shell: bash
-        run: cmake -E make_directory ${{ github.workspace }}/build
+  #     - name: Create build environment
+  #       shell: bash
+  #       run: cmake -E make_directory ${{ github.workspace }}/build
 
-      - name: Configure CMake
-        shell: bash
-        run: cmake -S . -B build
-                -G "$CMAKE_GENERATOR"
-                -DCMAKE_BUILD_TYPE=$LINUX_BUILD_TYPE
-                -DMYSQLCLIENT_STATIC_LINKING=true
-                -DWITH_UNIXODBC=1
-                -DENABLE_UNIT_TESTS=TRUE
-                -DENABLE_INTEGRATION_TESTS=FALSE
+  #     - name: Configure CMake
+  #       shell: bash
+  #       run: cmake -S . -B build
+  #               -G "$CMAKE_GENERATOR"
+  #               -DCMAKE_BUILD_TYPE=$LINUX_BUILD_TYPE
+  #               -DMYSQLCLIENT_STATIC_LINKING=true
+  #               -DWITH_UNIXODBC=1
+  #               -DENABLE_UNIT_TESTS=TRUE
+  #               -DENABLE_INTEGRATION_TESTS=FALSE
 
-      # Build driver
-      - name: Build driver
-        working-directory: ${{ github.workspace }}/build
-        shell: bash
-        run: cmake --build . --config $LINUX_BUILD_TYPE
+  #     # Build driver
+  #     - name: Build driver
+  #       working-directory: ${{ github.workspace }}/build
+  #       shell: bash
+  #       run: cmake --build . --config $LINUX_BUILD_TYPE
 
-      # Test driver
-      - name: Run failover tests on Linux
-        if: success()
-        working-directory: ${{ github.workspace }}/build/testing
-        shell: bash
-        run: ctest --output-on-failure
+  #     # Test driver
+  #     - name: Run failover tests on Linux
+  #       if: success()
+  #       working-directory: ${{ github.workspace }}/build/testing
+  #       shell: bash
+  #       run: ctest --output-on-failure
 
-      # Upload artifacts
-      - name: Upload build artifacts - Binaries
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: linux-failover-binaries
-          path: ${{ github.workspace }}/build/bin/
-      - name: Upload build artifacts - Libraries
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: linux-failover-libraries
-          path: ${{ github.workspace }}/build/lib/
-      - name: Upload test artifacts
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: linux-failover-results
-          path: ${{ github.workspace }}/build/testing/Testing/Temporary/LastTest.log
+  #     # Upload artifacts
+  #     - name: Upload build artifacts - Binaries
+  #       if: always()
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: linux-failover-binaries
+  #         path: ${{ github.workspace }}/build/bin/
+  #     - name: Upload build artifacts - Libraries
+  #       if: always()
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: linux-failover-libraries
+  #         path: ${{ github.workspace }}/build/lib/
+  #     - name: Upload test artifacts
+  #       if: always()
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: linux-failover-results
+  #         path: ${{ github.workspace }}/build/testing/Testing/Temporary/LastTest.log
 
   build-mac:
     name: MacOS
