chore: rebase 8.1.0

diff --git a/.github/workflows/failover.yml b/.github/workflows/failover.yml
--- a/.github/workflows/failover.yml
+++ b/.github/workflows/failover.yml
@@ -24,9 +24,9 @@ env:
 jobs:
   build-windows:
     name: Windows
-    runs-on: windows-2019
+    runs-on: windows-latest
     env:
-      CMAKE_GENERATOR: Visual Studio 16 2019
+      CMAKE_GENERATOR: Visual Studio 17 2022
       MYSQL_DIR: C:/mysql-${{ vars.MYSQL_VERSION }}-winx64
     steps:
       - name: Checkout source code
@@ -35,8 +35,8 @@ jobs:
       # Configure build environment/dependencies
       - name: Install MySQL client libs and include files
         run: |
-          curl -L https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ vars.MYSQL_VERSION }}-winx64.zip -o mysql.zip
-          curl -L https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ vars.MYSQL_VERSION }}-winx64-debug-test.zip -o mysql-debug.zip
+          curl -L https://dev.mysql.com/get/Downloads/MySQL-8.1/mysql-${{ vars.MYSQL_VERSION }}-winx64.zip -o mysql.zip
+          curl -L https://dev.mysql.com/get/Downloads/MySQL-8.1/mysql-${{ vars.MYSQL_VERSION }}-winx64-debug-test.zip -o mysql-debug.zip
           unzip -d C:/ mysql.zip
           mkdir C:/mysql-${{ vars.MYSQL_VERSION }}-winx64-debug
           unzip -d C:/mysql-${{ vars.MYSQL_VERSION }}-winx64-debug mysql-debug.zip
@@ -209,125 +209,125 @@ jobs:
           name: linux-failover-results
           path: ${{ github.workspace }}/build/unit_testing/Testing/Temporary/LastTest.log
 
-  build-mac:
-    name: MacOS
-    runs-on: macos-13
-    env:
-      CMAKE_GENERATOR: Unix Makefiles
-      ODBC_DM_INCLUDES: /usr/local/include
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-
-      # Configure build environment/dependencies
-      # Removing some /usr/local/bin files to avoid symlink issues wih brew update
-      - name: Install MySQL client libs & other dependencies
-        run: |
-          rm '/usr/local/bin/2to3'
-          rm '/usr/local/bin/2to3-3.11'
-          rm '/usr/local/bin/idle3'
-          rm '/usr/local/bin/idle3.11'
-          rm '/usr/local/bin/pydoc3'
-          rm '/usr/local/bin/pydoc3.11'
-          rm '/usr/local/bin/python3'
-          rm '/usr/local/bin/python3-config'
-          rm '/usr/local/bin/python3.11'
-          rm '/usr/local/bin/python3.11-config'
-
-          brew update
-          brew unlink unixodbc
-          brew install libiodbc mysql-client
-          brew link --overwrite --force libiodbc
-
-          brew install openssl@1.1
-          rm -f /usr/local/lib/libssl.1.1.dylib
-          rm -f /usr/local/lib/libcrypto.1.1.dylib
-          ln -s /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /usr/local/lib/
-          ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /usr/local/lib/
-
-          source /Users/runner/.bash_profile
-          
-          curl -L https://dev.mysql.com/get/Downloads/MySQL-8.0/mysql-${{ vars.MYSQL_VERSION }}-macos13-x86_64.tar.gz -o mysql.tar.gz
-          tar -xzvf mysql.tar.gz
-
-      - name: Cache AWS SDK libraries
-        id: cache-dynamic-aws-sdk
-        uses: actions/cache@v4
-        with:
-          path: |
-            aws_sdk
-          key: ${{ runner.os }}-aws-sdk-dynamic-lib
-
-      - name: Build and install AWS SDK C++
-        working-directory: ./scripts
-        if: steps.cache-dynamic-aws-sdk.outputs.cache-hit != 'true'
-        run: |
-          ./build_aws_sdk_unix.sh $MAC_BUILD_TYPE
-      
-      - name: Create build environment
-        shell: bash
-        run: cmake -E make_directory ${{ github.workspace }}/build
-
-      - name: Configure CMake
-        shell: bash
-        run: cmake -S . -B build
-                -G "$CMAKE_GENERATOR"
-                -DCMAKE_BUILD_TYPE=$MAC_BUILD_TYPE
-                -DMYSQLCLIENT_STATIC_LINKING=true
-                -DODBC_INCLUDES=$ODBC_DM_INCLUDES
-                -DENABLE_UNIT_TESTS=TRUE
-                -DENABLE_INTEGRATION_TESTS=FALSE
-                -DMYSQL_DIR=./mysql-${{ vars.MYSQL_VERSION }}-macos13-x86_64
-
-      # Build driver
-      - name: Build driver
-        working-directory: ${{ github.workspace }}/build
-        shell: bash
-        run: |
-          export LIBRARY_PATH=$LIBRARY_PATH:$(brew --prefix zstd)/lib/
-          cmake --build .
-          ln -s /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /Users/runner/work/aws-mysql-odbc/aws-mysql-odbc/build/unit_testing/
-          ln -s /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /Users/runner/work/aws-mysql-odbc/aws-mysql-odbc/build/unit_testing/bin/
-          ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /Users/runner/work/aws-mysql-odbc/aws-mysql-odbc/build/unit_testing/
-          ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /Users/runner/work/aws-mysql-odbc/aws-mysql-odbc/build/unit_testing/bin/
-
-      # Test driver
-      - name: Run driver tests
-        if: success()
-        working-directory: ${{ github.workspace }}/build/unit_testing
-        shell: bash
-        run: ctest --output-on-failure
-
-      - name: Check memory leaks
-        if: always()
-        working-directory: ${{ github.workspace }}/build/unit_testing/bin
-        run:  |
-          leaks -atExit -- ./unit_testing > ../leaks_unit_testing.txt
-          export is_leaking=$?
-          if (( $is_leaking != 0 )); then echo $is_leaking; exit 1; else echo "no memory leaks"; fi;
-
-      # Upload artifacts
-      - name: Upload build artifacts - Binaries
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: macos-binaries
-          path: ${{ github.workspace }}/build/bin/
-      - name: Upload build artifacts - Libraries
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: macos-libraries
-          path: ${{ github.workspace }}/build/lib/
-      - name: Upload test artifacts
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: macos-failover-results
-          path: ${{ github.workspace }}/build/unit_testing/Testing/Temporary/LastTest.log
-      - name: Upload memory leaks check
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: macos-memory-leaks-results
-          path: ${{ github.workspace }}/build/unit_testing/leaks_unit_testing.txt
+#  build-mac:
+#    name: MacOS
+#    runs-on: macos-13
+#    env:
+#      CMAKE_GENERATOR: Unix Makefiles
+#      ODBC_DM_INCLUDES: /usr/local/include
+#    steps:
+#      - name: Checkout source code
+#        uses: actions/checkout@v4
+#
+#      # Configure build environment/dependencies
+#      # Removing some /usr/local/bin files to avoid symlink issues wih brew update
+#      - name: Install MySQL client libs & other dependencies
+#        run: |
+#          rm '/usr/local/bin/2to3'
+#          rm '/usr/local/bin/2to3-3.11'
+#          rm '/usr/local/bin/idle3'
+#          rm '/usr/local/bin/idle3.11'
+#          rm '/usr/local/bin/pydoc3'
+#          rm '/usr/local/bin/pydoc3.11'
+#          rm '/usr/local/bin/python3'
+#          rm '/usr/local/bin/python3-config'
+#          rm '/usr/local/bin/python3.11'
+#          rm '/usr/local/bin/python3.11-config'
+#
+#          brew update
+#          brew unlink unixodbc
+#          brew install libiodbc mysql-client
+#          brew link --overwrite --force libiodbc
+#
+#          brew install openssl@1.1
+#          rm -f /usr/local/lib/libssl.1.1.dylib
+#          rm -f /usr/local/lib/libcrypto.1.1.dylib
+#          ln -s /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /usr/local/lib/
+#          ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /usr/local/lib/
+#
+#          source /Users/runner/.bash_profile
+#
+#          curl -L https://dev.mysql.com/get/Downloads/MySQL-8.1/mysql-${{ vars.MYSQL_VERSION }}-macos13-x86_64.tar.gz -o mysql.tar.gz
+#          tar -xzvf mysql.tar.gz
+#
+#      - name: Cache AWS SDK libraries
+#        id: cache-dynamic-aws-sdk
+#        uses: actions/cache@v4
+#        with:
+#          path: |
+#            aws_sdk
+#          key: ${{ runner.os }}-aws-sdk-dynamic-lib
+#
+#      - name: Build and install AWS SDK C++
+#        working-directory: ./scripts
+#        if: steps.cache-dynamic-aws-sdk.outputs.cache-hit != 'true'
+#        run: |
+#          ./build_aws_sdk_unix.sh $MAC_BUILD_TYPE
+#
+#      - name: Create build environment
+#        shell: bash
+#        run: cmake -E make_directory ${{ github.workspace }}/build
+#
+#      - name: Configure CMake
+#        shell: bash
+#        run: cmake -S . -B build
+#                -G "$CMAKE_GENERATOR"
+#                -DCMAKE_BUILD_TYPE=$MAC_BUILD_TYPE
+#                -DMYSQLCLIENT_STATIC_LINKING=true
+#                -DODBC_INCLUDES=$ODBC_DM_INCLUDES
+#                -DENABLE_UNIT_TESTS=TRUE
+#                -DENABLE_INTEGRATION_TESTS=FALSE
+#                -DMYSQL_DIR=./mysql-${{ vars.MYSQL_VERSION }}-macos13-x86_64
+#
+#      # Build driver
+#      - name: Build driver
+#        working-directory: ${{ github.workspace }}/build
+#        shell: bash
+#        run: |
+#          export LIBRARY_PATH=$LIBRARY_PATH:$(brew --prefix zstd)/lib/
+#          cmake --build .
+#          ln -s /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /Users/runner/work/aws-mysql-odbc/aws-mysql-odbc/build/unit_testing/
+#          ln -s /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib /Users/runner/work/aws-mysql-odbc/aws-mysql-odbc/build/unit_testing/bin/
+#          ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /Users/runner/work/aws-mysql-odbc/aws-mysql-odbc/build/unit_testing/
+#          ln -s /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib /Users/runner/work/aws-mysql-odbc/aws-mysql-odbc/build/unit_testing/bin/
+#
+#      # Test driver
+#      - name: Run driver tests
+#        if: success()
+#        working-directory: ${{ github.workspace }}/build/unit_testing
+#        shell: bash
+#        run: ctest --output-on-failure
+#
+#      - name: Check memory leaks
+#        if: always()
+#        working-directory: ${{ github.workspace }}/build/unit_testing/bin
+#        run:  |
+#          leaks -atExit -- ./unit_testing > ../leaks_unit_testing.txt
+#          export is_leaking=$?
+#          if (( $is_leaking != 0 )); then echo $is_leaking; exit 1; else echo "no memory leaks"; fi;
+#
+#      # Upload artifacts
+#      - name: Upload build artifacts - Binaries
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: macos-binaries
+#          path: ${{ github.workspace }}/build/bin/
+#      - name: Upload build artifacts - Libraries
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: macos-libraries
+#          path: ${{ github.workspace }}/build/lib/
+#      - name: Upload test artifacts
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: macos-failover-results
+#          path: ${{ github.workspace }}/build/unit_testing/Testing/Temporary/LastTest.log
+#      - name: Upload memory leaks check
+#        if: always()
+#        uses: actions/upload-artifact@v4
+#        with:
+#          name: macos-memory-leaks-results
+#          path: ${{ github.workspace }}/build/unit_testing/leaks_unit_testing.txt
